### ISSUE TITLE
Bluetooth pairs then disconnects right way

### ISSUE THREAD

**Issue by justinpogge** [pttuan/kaleido_sniper#1]
this may be an issue with the board, not the code, but after flashing the script, I tried connecting to my roaster between the board and the touch screen and the screen did not come on and my computer could not find the bluetooth connection. i then tried just plugging the usb into a wall wart and it connected for a second and then would disappear. I noticed when flashing the code onto the board that the ESP32 was super warm. possibly a bad board?

**Comment by pttuan** [comment]
Hello,
I can't follow your issue. It is best if you have diagram of your connection between Kaleido, computer, pad...
For bluetooth issue, because it is Bluetooth BLE, Windows may show disconnected but it should connect again when you use Artisan to open connection.

**Comment by justinpogge** [comment]
I have connected the the Dupont connectors to the ESP32 per your instructions along with the optional USB connection for the original Kaleido pad. the ESP32 has only one 5v pin, so I connected both USB connectors to that pin. I purchased the recommended ESP32 from Amazon and the USB to Dupont wires in the description. so the connections and pins should be correct.  
have you experienced heat issues with your board? I have ordered a replacement one in case its a faulty board. 
have you had issues with the board overheating?

**Comment by pttuan** [comment]
My board is cool to touch so  yours may have problem.

**Comment by justinpogge** [comment]
Purchased a new board not in still unable to get it working properly. I know my Kaleido is an early version with an early version of the screen. Is it probable that the control board and screen are not compatible? Is there a version number on your Kaleido board?

**Comment by pttuan** [comment]
My board came with 7" Pad, not sure what version of it. If you have 4" pad then that will be an issue

**Comment by jedimaster2001** [comment]
not sure if this relates to your issue but I see that in linux, if I tried to connect it as an "audio and input profile" it would connect and disconnect right away. However, when I connect it as "serial port" then the connection is established. Not sure how it is in Windows or Mac.

**Comment by justinpogge** [comment]
im using a windows computer, but I also have a linux system i can try. I am still trying to figure out if my roaster has the same board in it as the one being used here and if this mod will even work.
