### ISSUE TITLE
Would this code work with M1?

### ISSUE THREAD

**Issue by jedimaster2001** [pttuan/kaleido_sniper#2]

**Comment by sttechnologyprocoding** [comment]
@jedimaster2001 Hello, have you been able to use this code with M1? I use M1, with 7" pad (standard version), tried connecting laptop to esp32 via bluetooth, configured artisan and pressed ON but my M1 does not work. ET BT indicators are not received.

**Comment by pttuan** [comment]
It works on M1 with 7" pad reported by a user. I am not guaranty it will work with the latest M1. If you are not familiar with DIY project (electric and programming knowledge) then I wouldn't suggest this project.

**Comment by sttechnologyprocoding** [comment]
Sorry, I just read this comment now. My M1 was bought around May 2022 so I think it is not the latest version

**Comment by jedimaster2001** [comment]
Hi, thank you for your response. I wanted to check before getting the parts. I bought the parts regardless, and got it working on my M1. Your instructions were really good.

**Comment by pttuan** [comment]
> Hi, thank you for your response. I wanted to check before getting the parts. I bought the parts regardless, and got it working on my M1. Your instructions were really good.

Good to hear that it is working for you.
